### ISSUE TITLE
Failure from math.h on Linux: macro invocations with empty parameter

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/melange#27]
@wvdschel reported that he is having a melange failure on Linux when processing ``math.h``.

The problematic code can be reduced to:

```c
#define __MATHCALL(function,suffix, args)       \
  __MATHDECL (_Mdouble_,function,suffix, args)
#define __MATHDECL(type, function,suffix, args) \
  __MATHDECL_1(type, function,suffix, args); \
  __MATHDECL_1(type, __CONCAT(__,function),suffix, args)
#define __MATHCALLX(function,suffix, args, attrib)      \
  __MATHDECLX (_Mdouble_,function,suffix, args, attrib)
#define __MATHDECLX(type, function,suffix, args, attrib) \
  __MATHDECL_1(type, function,suffix, args) __attribute__ (attrib); \
  __MATHDECL_1(type, __CONCAT(__,function),suffix, args) __attribute__ (attrib)
#define __MATHDECL_1(type, function,suffix, args) \
  extern type __MATH_PRECNAME(function,suffix) args __THROW
#define _Mdouble_               double
#define __MATH_PRECNAME(name,r) __CONCAT(name,r)
#define __CONCAT(x,y)   x ## y
#define __THROW

__MATHCALL (acos,, (_Mdouble_ __x));
```

Specifically, the problem is with the empty parameter in ``__MATHCALL (acos,, (_Mdouble_ __x));``.

**Comment by waywardmonkeys** [comment]
This is probably an issue with the logic in ``get-macro-params`` from ``melange-core/c-lexer-cpp.dylan``.

The current version of this code can be seen at https://github.com/dylan-lang/melange/blob/ed875f582f4fdc424f02bc463d869d42ed52cc08/melange-core/c-lexer-cpp.dylan#L109-L133

**Comment by wvdschel** [comment]
A further reduced test case:
```c
#define __MATHCALL(function,suffix, args) extern double function ## suffix args 
__MATHCALL (acos,, (int __x));
```

The concatenation seems to be important.

**Comment by wvdschel** [comment]
While playing around, I ran into the following as well, which may be a different issue with the same cause:

```c
#define MANGLE(module, name) module ## name
#define DEFUN(name, module, args) extern void MANGLE(module, name) args

DEFUN(foo,, (int num));
DEFUN(bar, stdlib, (int num));
```

Which `GNU cpp` correctly translates to:
```c
extern void foo (int num);
extern void stdlibbar (int num);
```

Yet `melange` makes into:

```dylan
define C-function voidfoo
  input parameter num_ :: <C-signed-int>;
  result res :: <C-signed-int>;
  c-name: "voidfoo";
end;

define C-function stdlibbar
  input parameter num_ :: <C-signed-int>;
  c-name: "stdlibbar";
end;
```

Note that Melange failed to insert a space between void and foo, and subsequently parsed them as a single token. I've also run into examples where this causes an error like in the original example (`Parse error at or before voidfoo`).

**Comment by wvdschel** [comment]
Just as a note for myself later. I'm entertaining two possible solutions:

1. Adding an <empty-token> class to emit from the pre-processor so that we can consume this during concatenation and ignore it otherwise. This is easy to do and should not require a lot of changes.
2. Address the issue properly by removing the double pound operator from the C lexer, and into the CPP lexer where it belongs (probably in check-cpp-expansion). This is harder and requires more work.
